export const seedOpportunities = [
  { id: 'food-relief-packing-assistant', title: 'Food Relief Packing Assistant', organisation: 'VolunteerConnect', cause: 'Nutrition Support', location: 'Clayton', deliveryMode: 'On-site', commitment: 'One-off', schedule: 'Saturday, 10:00 am - 1:00 pm', duration: '3 hours', experience: 'No experience required', summary: 'Prepare balanced food parcels for older residents who may have difficulty shopping or accessing nutritious food.' },
  { id: 'digital-skills-tutor', title: 'Digital Skills Tutor', organisation: 'VolunteerConnect', cause: 'Digital Inclusion', location: 'Online', deliveryMode: 'Hybrid', commitment: 'Weekly', schedule: 'Wednesday, 5:30 pm - 7:00 pm', duration: '1.5 hours weekly', experience: 'Some experience useful', summary: 'Help older adults use video calls, telehealth portals and everyday online services with greater confidence.' },
  { id: 'community-garden-working-bee', title: 'Community Garden Working Bee', organisation: 'VolunteerConnect', cause: 'Active Ageing', location: 'Oakleigh', deliveryMode: 'On-site', commitment: 'One-off', schedule: 'Sunday, 9:00 am - 12:00 pm', duration: '3 hours', experience: 'No experience required', summary: 'Maintain an accessible garden where older adults can enjoy gentle activity, fresh produce and conversation.' },
  { id: 'companion-visitor', title: 'Companion Visitor', organisation: 'VolunteerConnect', cause: 'Social Connection', location: 'Caulfield', deliveryMode: 'On-site', commitment: 'Weekly', schedule: 'Flexible weekday afternoons', duration: '1 hour weekly', experience: 'No experience required', summary: 'Spend an hour each week talking, reading or playing board games with an older adult experiencing social isolation.' },
  { id: 'wildlife-content-helper', title: 'Pet Wellbeing Content Helper', organisation: 'VolunteerConnect', cause: 'Pet Wellbeing', location: 'Online', deliveryMode: 'Remote', commitment: 'Flexible', schedule: 'Choose 2 hours each week', duration: '2 hours weekly', experience: 'Some experience useful', summary: 'Create clear pet care information that helps older pet owners find practical support and trusted services.' },
  { id: 'community-event-welcome-crew', title: 'Healthy Ageing Community Day Welcome Crew', organisation: 'VolunteerConnect', cause: 'Community Health', location: 'Dandenong', deliveryMode: 'On-site', commitment: 'One-off', schedule: 'Friday, 4:30 pm - 8:30 pm', duration: '4 hours', experience: 'No experience required', summary: 'Welcome older visitors and help them find free healthy ageing activities, information and local services.' },
]

